# Generated by Django 4.2.3 on 2023-08-07 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('season', models.IntegerField()),
                ('teams', models.IntegerField(null=True)),
                ('players', models.JSONField(null=True)),
                ('standings', models.JSONField()),
                ('first_match', models.DateTimeField()),
                ('last_match', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alternate_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=4)),
                ('logo', models.URLField()),
                ('icon', models.URLField()),
                ('primary_color', models.CharField(max_length=100, null=True)),
                ('secondary_color', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('teams', models.JSONField()),
                ('games', models.JSONField()),
                ('players', models.JSONField()),
                ('winner_id', models.IntegerField(null=True)),
                ('match_url', models.URLField()),
                ('slug', models.SlugField(blank=True, default='')),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='stats.segment')),
            ],
        ),
    ]
