# Generated by Django 4.2.3 on 2023-08-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='alternate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='primary_color',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
