# Generated by Django 4.2.3 on 2023-08-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_team_alternate_id_alter_team_primary_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alternate_id', models.IntegerField(blank=True, null=True)),
                ('headshot_url', models.URLField()),
                ('name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100, null=True)),
                ('number', models.IntegerField(null=True)),
                ('all_teams', models.JSONField()),
                ('heroes', models.JSONField()),
                ('stats', models.JSONField()),
                ('segment_stats', models.JSONField()),
                ('slug', models.SlugField(blank=True, default='')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='stats.team')),
            ],
        ),
    ]
