# Generated by Django 4.2.3 on 2023-08-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='headshot_url',
            field=models.URLField(null=True),
        ),
    ]
