# Generated by Django 4.2.3 on 2023-08-09 01:40
import django
from django.db import migrations, models
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_player_first_name_alter_player_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='standings',
            field=models.JSONField(null=True),
        ),
        migrations.RemoveField(
            model_name='segment',
            name='teams',
        ),
        migrations.AddField(
            model_name='segment',
            name='teams',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
