# Generated by Django 4.2.3 on 2023-08-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_segment_standings_alter_segment_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='first_match',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='last_match',
            field=models.DateTimeField(null=True),
        ),
    ]
