# Generated by Django 4.2.3 on 2023-08-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_alter_match_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.CharField(choices=[('W', 'west'), ('E', 'east'), ('C', 'contenders')], max_length=200, null=True),
        ),
    ]
