# Generated by Django 4.2.3 on 2023-08-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_alter_team_primary_color_alter_team_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='primary_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
