# Generated by Django 4.2.3 on 2023-08-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_alter_team_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_url',
            field=models.URLField(null=True),
        ),
    ]
