# Generated by Django 4.2.3 on 2023-09-15 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_award_alter_player_heroes_alter_player_segment_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='nominee',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='stats.player'),
        ),
        migrations.AddField(
            model_name='award',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='award',
            name='winner',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='end_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='start_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='games',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.JSONField(null=True),
        ),
    ]
