# Generated by Django 4.2.3 on 2023-09-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_award_nominee_award_player_award_slug_award_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='nominee',
        ),
        migrations.AddField(
            model_name='award',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='stats.team'),
        ),
    ]
