# Generated by Django 4.2.3 on 2023-09-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_remove_award_nominee_award_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(choices=[('League Champion', 'League Champion'), ('MVP', 'MVP'), ('Grand Finals MVP', 'Grand Finals MVP'), ('Dennis Hawelka Award', 'Dennis Hawelka Award'), ('Alarm Rookie of the Year', 'Alarm Rookie of the Year'), ('Role Star', 'Role Star')], max_length=300),
        ),
    ]
