# Generated by Django 4.2.3 on 2023-09-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_alter_award_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='winner',
        ),
    ]
