# Generated by Django 4.2.3 on 2023-09-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_remove_award_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='stats.player'),
        ),
        migrations.AlterField(
            model_name='award',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='stats.team'),
        ),
    ]
